/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Playlist } from '../../models/playlist';

export interface PlaylistControllerRemoveMember$Params {
  id: string;
  memberId: string;
}

export function playlistControllerRemoveMember(http: HttpClient, rootUrl: string, params: PlaylistControllerRemoveMember$Params, context?: HttpContext): Observable<StrictHttpResponse<Playlist>> {
  const rb = new RequestBuilder(rootUrl, playlistControllerRemoveMember.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('memberId', params.memberId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Playlist>;
    })
  );
}

playlistControllerRemoveMember.PATH = '/api/playlist/{id}/member/{memberId}';
