/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedPlaylistsDto } from '../../models/paginated-playlists-dto';

export interface PlaylistControllerFindAll$Params {
  limit?: number;
  page?: number;
}

export function playlistControllerFindAll(http: HttpClient, rootUrl: string, params?: PlaylistControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedPlaylistsDto>> {
  const rb = new RequestBuilder(rootUrl, playlistControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('limit', params.limit, {});
    rb.query('page', params.page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedPlaylistsDto>;
    })
  );
}

playlistControllerFindAll.PATH = '/api/playlist';
