/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Playlist } from '../../models/playlist';
import { SharePlaylistDto } from '../../models/share-playlist-dto';

export interface PlaylistControllerShare$Params {
  id: string;
      body: SharePlaylistDto
}

export function playlistControllerShare(http: HttpClient, rootUrl: string, params: PlaylistControllerShare$Params, context?: HttpContext): Observable<StrictHttpResponse<Playlist>> {
  const rb = new RequestBuilder(rootUrl, playlistControllerShare.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Playlist>;
    })
  );
}

playlistControllerShare.PATH = '/api/playlist/{id}/share';
