/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Friendship } from '../../models/friendship';

export interface FriendshipControllerFindPendingSent$Params {
}

export function friendshipControllerFindPendingSent(http: HttpClient, rootUrl: string, params?: FriendshipControllerFindPendingSent$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Friendship>>> {
  const rb = new RequestBuilder(rootUrl, friendshipControllerFindPendingSent.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Friendship>>;
    })
  );
}

friendshipControllerFindPendingSent.PATH = '/api/friendship/requests/sent';
