/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Friendship } from '../../models/friendship';
import { SendRequestDto } from '../../models/send-request-dto';

export interface FriendshipControllerSendRequest$Params {
      body: SendRequestDto
}

export function friendshipControllerSendRequest(http: HttpClient, rootUrl: string, params: FriendshipControllerSendRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<Friendship>> {
  const rb = new RequestBuilder(rootUrl, friendshipControllerSendRequest.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Friendship>;
    })
  );
}

friendshipControllerSendRequest.PATH = '/api/friendship/request';
