/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Friendship } from '../../models/friendship';
import { RespondRequestDto } from '../../models/respond-request-dto';

export interface FriendshipControllerRespondToRequest$Params {
  id: string;
      body: RespondRequestDto
}

export function friendshipControllerRespondToRequest(http: HttpClient, rootUrl: string, params: FriendshipControllerRespondToRequest$Params, context?: HttpContext): Observable<StrictHttpResponse<Friendship>> {
  const rb = new RequestBuilder(rootUrl, friendshipControllerRespondToRequest.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Friendship>;
    })
  );
}

friendshipControllerRespondToRequest.PATH = '/api/friendship/{id}/respond';
