/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserSearchResultDto } from '../../models/user-search-result-dto';

export interface FriendshipControllerSearch$Params {
  username: string;
}

export function friendshipControllerSearch(http: HttpClient, rootUrl: string, params: FriendshipControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserSearchResultDto>>> {
  const rb = new RequestBuilder(rootUrl, friendshipControllerSearch.PATH, 'get');
  if (params) {
    rb.query('username', params.username, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserSearchResultDto>>;
    })
  );
}

friendshipControllerSearch.PATH = '/api/friendship/search';
