/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthResponseDto } from './models/auth-response-dto';
export type { ChatDto } from './models/chat-dto';
export type { CreateMusicDto } from './models/create-music-dto';
export type { CreatePlaylistDto } from './models/create-playlist-dto';
export type { Friendship } from './models/friendship';
export type { LoginDto } from './models/login-dto';
export type { Music } from './models/music';
export type { PaginatedMusicDto } from './models/paginated-music-dto';
export type { PaginatedPlaylistsDto } from './models/paginated-playlists-dto';
export type { Playlist } from './models/playlist';
export type { RegisterDto } from './models/register-dto';
export type { RespondRequestDto } from './models/respond-request-dto';
export type { SendRequestDto } from './models/send-request-dto';
export type { UpdateMusicDto } from './models/update-music-dto';
export type { UpdatePlaylistDto } from './models/update-playlist-dto';
export type { User } from './models/user';
