/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Music } from '../../models/music';
import { UpdateMusicDto } from '../../models/update-music-dto';

export interface MusicControllerUpdate$Params {
  id: string;
      body: UpdateMusicDto
}

export function musicControllerUpdate(http: HttpClient, rootUrl: string, params: MusicControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<Music>> {
  const rb = new RequestBuilder(rootUrl, musicControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Music>;
    })
  );
}

musicControllerUpdate.PATH = '/api/music/{id}';
