/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedMusicDto } from '../../models/paginated-music-dto';

export interface MusicControllerFindAll$Params {
  limit?: number;
  page?: number;
}

export function musicControllerFindAll(http: HttpClient, rootUrl: string, params?: MusicControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedMusicDto>> {
  const rb = new RequestBuilder(rootUrl, musicControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('limit', params.limit, {});
    rb.query('page', params.page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedMusicDto>;
    })
  );
}

musicControllerFindAll.PATH = '/api/music';
