/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Music } from '../../models/music';

export interface MusicControllerFindOne$Params {
  id: string;
}

export function musicControllerFindOne(http: HttpClient, rootUrl: string, params: MusicControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<Music>> {
  const rb = new RequestBuilder(rootUrl, musicControllerFindOne.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Music>;
    })
  );
}

musicControllerFindOne.PATH = '/api/music/{id}';
