/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Friendship {
  addressee: User;
  addresseeId: string;
  createdAt: string;
  id: string;
  requester: User;
  requesterId: string;
  status: 'pending' | 'accepted' | 'declined';
}
