/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Playlist } from '../models/playlist';
export interface PaginatedPlaylistsDto {
  data: Array<Playlist>;
  limit: number;
  page: number;
  total: number;
}
