/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Music } from '../models/music';
export interface PaginatedMusicDto {
  data: Array<Music>;
  limit: number;
  page: number;
  total: number;
}
