/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Music } from '../models/music';
import { User } from '../models/user';
export interface Playlist {
  createdAt: string;
  creator: User;
  creatorId: string;
  id: string;
  isDefault: boolean;
  members: Array<User>;
  musics: Array<Music>;
  name: string;
}
