/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProfileDto {
  createdAt: string;
  email: string;
  generationsRemaining: number;
  id: string;
  monthlyAllowance: number;
  plan: string;
  username: string;
}
