/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterDto {
  birthDate: string;
  consent: boolean;
  email: string;
  parentEmail?: string;
  parentalConsent?: boolean;
  password: string;
  username: string;
}
