/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Music } from '../models/music';
import { Playlist } from '../models/playlist';
export interface User {
  createdAt: string;
  createdPlaylists: Array<Playlist>;
  email: string;
  id: string;
  musics: Array<Music>;
  password: string;
  sharedPlaylists: Array<Playlist>;
  username: string;
}
